# Generated by Django 4.2 on 2023-08-30 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_comments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='comment_type',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='object_id',
        ),
    ]
