# Generated by Django 4.2 on 2023-12-20 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_votes', '0003_alter_vote_content_type'),
        ('app_comments', '0002_remove_comment_comment_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='downvotes',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='upvotes',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='downvotes',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='upvotes',
        ),
        migrations.AddField(
            model_name='answer',
            name='votes',
            field=models.ManyToManyField(related_name='answer_votes', to='app_votes.vote'),
        ),
        migrations.AddField(
            model_name='comment',
            name='votes',
            field=models.ManyToManyField(related_name='comment_votes', to='app_votes.vote'),
        ),
    ]
