# Generated by Django 4.2 on 2023-12-20 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_comments', '0003_remove_answer_downvotes_remove_answer_upvotes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='votes',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='votes',
        ),
    ]
