# Generated by Django 4.2 on 2023-12-20 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_posts', '0002_remove_post_downvotes_remove_post_upvotes_post_votes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='votes',
        ),
    ]
