# Generated by Django 4.2 on 2023-12-21 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_communities', '__first__'),
        ('app_posts', '0003_remove_post_votes'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='hive',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='app_communities.hive'),
            preserve_default=False,
        ),
    ]
