# Generated by Django 4.2 on 2024-01-03 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_posts', '0004_post_hive'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
