# Generated by Django 4.2 on 2023-08-14 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_profiles', '0002_profile_first_name_profile_job_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='last_name',
        ),
    ]
