# Generated by Django 4.2 on 2023-08-16 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_profiles', '0004_remove_profile_id_profile_company_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
