# Generated by Django 5.0.1 on 2024-02-27 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_profiles', '0010_profile_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='has_completed_questionnaire',
            field=models.BooleanField(default=False),
        ),
    ]
