# Generated by Django 5.0.1 on 2024-03-03 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_profiles', '0011_profile_has_completed_questionnaire'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='has_completed_questionnaire',
        ),
    ]
