# Generated by Django 4.2 on 2024-03-03 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_profiles', '0012_remove_profile_has_completed_questionnaire'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='has_completed_questionnaire',
            field=models.BooleanField(default=False),
        ),
    ]
