# Generated by Django 4.2 on 2024-03-03 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_profiles', '0013_profile_has_completed_questionnaire'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='has_completed_questionnaire',
        ),
    ]
